package dev.phoenix.chat.ui

import com.formdev.flatlaf.FlatDarkLaf
import dev.phoenix.chat.Client
import dev.phoenix.chat.ui.TabCloseCallbackHolder.*
import dev.phoenix.chat.ui.TabPanel
import java.awt.*
import java.awt.event.ActionEvent
import java.awt.image.BufferedImage
import java.io.IOException
import java.util.*
import java.util.function.BiConsumer
import java.util.function.IntConsumer
import javax.swing.*
import javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER
import javax.swing.text.BadLocationException
import javax.swing.text.DefaultCaret
import javax.swing.text.html.HTMLDocument
import javax.swing.text.html.HTMLEditorKit

/**
 * @author _kritanta
 * TODO: Refactor Everything
 * 
 * This is by far the messiest, worst class(es) in the project. It's already scary to touch in certain parts.
 */
class ChatFrame : JFrame() {
    var tabsByName: MutableMap<String, Component> = HashMap()

    fun destroyTabs() {
        while (tabbedPane.tabCount > 0)
        {
            tabbedPane.remove(0)
        }
        tabsByName = HashMap()
    }

    fun createTabWithName(name: String) {
        val tab = TabPanel(name)
        tabbedPane.addTab(name, tab)
        tabsByName[name] = tab
    }

    fun addLineToTabWithName(name: String?, message: String) {

        if (!tabsByName.containsKey(name) && name != null)
            createTabWithName(name)
            
        val tab = tabsByName[name] as TabPanel? 
        tab!!.appendToChatPane(message)
    }

    // rest of this file is autogenerated, not much worth looking at here.

    private fun initComponents() {

        val contentPane = contentPane

        val contentPaneLayout = GroupLayout(contentPane)
        contentPane.layout = contentPaneLayout
        contentPaneLayout.setHorizontalGroup(
                contentPaneLayout.createParallelGroup()
                        .addComponent(tabbedPane)
        )

        contentPaneLayout.setVerticalGroup(
                contentPaneLayout.createParallelGroup()
                        .addComponent(tabbedPane)
        )

        pack()

        setLocationRelativeTo(owner)
        preferredSize = Dimension(800, 500)
        setSize(800, 500)

        tabbedPane.putClientProperty("JTabbedPane.tabClosable", true)

        tabbedPane.putClientProperty("JTabbedPane.tabCloseCallback", consumer)


        // Options
        // - 

        var toolbar = JToolBar()
        var options = JMenu("Options")
        var filter = JMenu("Filter")

    }

    val tabbedPane = JTabbedPane()

    init {
        FlatDarkLaf.install()
        println(UIManager.getLookAndFeel().name)
        initComponents()
        title = "Chat"
        val icon: Image = ImageIcon(getClass().getResource("/icon.png"))
        iconImage = icon
        SwingUtilities.updateComponentTreeUI(contentPane)
        defaultCloseOperation = DISPOSE_ON_CLOSE
        this.isVisible = true
    }
}